env = "development"

[default_redis]
    [default_redis.development]
    host="127.0.0.1"
    port="6379"
    password="123456"
    maxIdle=10
    maxOpen=3000
    connect_timeout=3
    read_timeout=10
    write_timeout=3
    idle_timeout=300

    [default_redis.production]
    hhost="127.0.0.1"
    port="6379"
    password="123456"
    maxIdle=100
    maxOpen=3000
    connect_timeout=3
    read_timeout=10
    write_timeout=3
    idle_timeout=300